language: python
sudo: required
dist: trusty

python:
  - "2.7"
  - "3.4"

virtualenv:
  system_site_packages: true

matrix:
  exclude:
    - env: QT_API=pyqt5
      python: "2.7"

env:
 - QT_API=pyqt4
 - QT_API=pyqt5

before_install:
    - "export DISPLAY=:99.0"
    - "sh -e /etc/init.d/xvfb start"

install:
 - sudo apt-get update

 # Xvfb
 - sudo apt-get install -y xvfb

 # Qt
 - python scripts/install-qt.py

 # others
 - pip install coveralls --use-wheel

 # install pyqode.qt from master branch (pyqode.core thighly tied to pyqode.qt)
 - pip install git+https://github.com/pyQode/pyqode.qt

script:
 - pip install -e .
 - catchsegv python setup.py test -a "--cov pyqode"

after_success:
 - coveralls
