language: python
python:
  - "2.7"
  - "3.3"
before_install:
 - sudo apt-get install -qq python-pyside
 - sudo apt-get install -qq python-qt4
 - sudo apt-get install -qq python3-pyside
 - sudo apt-get install -qq python3-pyqt4
 - sudo pip install pygments
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
script:
  - python test.py --PyQt
  - python test.py --PySide