language: python
python:
 - "3.2"
env:
 - TOXENV=py32
 - TOXENV=py34
 - TOXENV=cov
matrix:
    allow_failures:
        - env: TOXENV=cov
virtualenv:
  system_site_packages: true
before_install:
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
install:
 - sudo apt-get install -qq python3-pyqt4 --fix-missing
 - pip install --quiet --use-mirrors tox
script:
  - tox
after_script:
    - if [ $TOXENV == "cov" ]; then
      pip install --quiet --use-mirrors coveralls;
      coveralls;
      fi