language: python
env:
    - TOXENV=py27
    - TOXENV=py32
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get update
 - sudo apt-get install -qq python-pyside --fix-missing
 - sudo apt-get install -qq python-qt4 --fix-missing
 - sudo apt-get install -qq python3-pyside --fix-missing
 - sudo apt-get install -qq python3-pyqt4 --fix-missing
 - "export DISPLAY=:99.0"
 - "sh -e /etc/init.d/xvfb start"
script:
  - tox