language: python
python:
  - "3.2"
virtualenv:
  system_site_packages: true
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
install:
  - sudo apt-get install -qq python3-pyqt4 --fix-missing
  - sudo pip install --quiet coveralls
script:
  - sudo pip install .
  - runtests.py
after_script:
  - coveralls
