language: python
python:
 - "2.7"
 - "3.2"
 - "3.3"
 - "3.4"
env:
  - QT_API=pyqt4
  - QT_API=pyqt5
  - COV=1
  - PEP8=1
matrix:
  allow_failures:
      - env: COV=1
      - env: PEP8=1
  exclude:
      - python: "2.7"
        env: COV=1
      - python: "2.7"
        env: PEP8=1
      - python: "3.2"
        env: COV=1
      - python: "3.2"
        env: PEP8=1
      - python: "3.3"
        env: COV=1
      - python: "3.3"
        env: PEP8=1
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  # Cached Downloads
  - sudo mkdir -p /downloads
  - sudo chmod a+rw /downloads
  - if [ ! -f /downloads/sip.tar.gz ];   then curl -L -o /downloads/sip.tar.gz http://sourceforge.net/projects/pyqt/files/sip/sip-4.16.5/sip-4.16.5.tar.gz; fi
  - if [ ! -f /downloads/pyqt4.tar.gz ]; then curl -L -o /downloads/pyqt4.tar.gz http://sourceforge.net/projects/pyqt/files/PyQt4/PyQt-4.11.3/PyQt-x11-gpl-4.11.3.tar.gz; fi
  - if [ ! -f /downloads/pyqt5.tar.gz ]; then curl -L -o /downloads/pyqt5.tar.gz http://sourceforge.net/projects/pyqt/files/PyQt5/PyQt-5.4.1/PyQt-gpl-5.4.1.tar.gz; fi
  # Builds
  - sudo mkdir -p /builds
  - sudo chmod a+rw /builds
install:
  - pip install git+https://github.com/pyQode/pyqode.qt.git
  - pip install pytest
  - pip install pytest-cov
  - pip install pytest-pep8
  # Qt4
  - sudo apt-get install -y libqt4-dev
  # Qt5
  - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test;
  - sudo apt-add-repository -y ppa:beineri/opt-qt541;
  - sudo apt-get -qq update;
  - sudo apt-get -qq install g++-4.9 libc6-i386 qt54tools qt54svg qt54webkit;
  - export CXX="g++-4.9";
  - export CC="gcc-4.9";
  - source /opt/qt54/bin/qt54-env.sh;
  # Builds
  - pushd /builds
  # SIP
  - tar xzf /downloads/sip.tar.gz --keep-newer-files
  - pushd sip-4.16.5
  - python configure.py
  - make
  - sudo make install
  - popd
  # PyQt4
  - tar xzf /downloads/pyqt4.tar.gz --keep-newer-files
  - pushd PyQt-x11-gpl-4.11.3
  - python configure.py -c --confirm-license --no-designer-plugin
  - make
  - sudo make install
  - popd
  # PyQt5
  - source /opt/qt54/bin/qt54-env.sh  # switch to Qt5
  - tar xzf /downloads/pyqt5.tar.gz --keep-newer-files
  - pushd PyQt-gpl-5.4.1
  - python configure.py -c --confirm-license --no-designer-plugin
  - make
  - sudo make install
  - popd
  # Builds Complete
  - popd
script:
  - if [$COV == "1"]; then
        py.test --cov pyqode test/
    elif [$PEP8 == "1"]; then
        py.test --pep8 -m pep8
    else
        py.test
    fi
after_script:
  - if [ $COV == "1" ]; then
        pip install --quiet coveralls;
        coveralls;
    fi
cache:
  directories:
    - /downloads
  apt: true
